# whenever someone changes the python code
#this will automatically review the code, syntax errors,indentation(linting) is correct or not.
name: Auto linter

on: 
  push:
    paths: 
      - "**/*.py"  # Fixed: Tracks all Python files across all subdirectories

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      #this step will automatically clone the code of the current branch into the runnner.
      - name: clone/checkout the code
        uses: actions/checkout@v7 # Note: v4 is the current stable version for checkout

      #this step will install the linter tool
      - name: install linter
        run: pip install ruff
